# Generated by Django 4.1.1 on 2022-09-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_category_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('life', '生活'), ('develop', '開発'), ('hero', 'ヒーロー'), ('other', 'その他')], default='other', max_length=100),
        ),
    ]
