# Generated by Django 3.2.15 on 2022-10-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_nickname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Nickname',
        ),
        migrations.RemoveField(
            model_name='post',
            name='nickname',
        ),
    ]
